# Generated by Django 2.2.28 on 2024-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
